// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmJWt7BPojonxt3_m1AtJtX8PIBasFeA',
    appId: '1:664320941491:android:7168d36db8d491d5693fc6',
    messagingSenderId: '664320941491',
    projectId: 'greenghana-app',
    storageBucket: 'greenghana-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48tUY_lC2nERfy61Lz1AppcqLmnh3Cf8',
    appId: '1:664320941491:ios:bdcd758c5dfd4496693fc6',
    messagingSenderId: '664320941491',
    projectId: 'greenghana-app',
    storageBucket: 'greenghana-app.appspot.com',
    androidClientId: '664320941491-fvuie4q8f4md0jv2o5m2lnjp60c94ina.apps.googleusercontent.com',
    iosClientId: '664320941491-87oqsnoor6uv4n3dhc3ku8b7f2jsojuj.apps.googleusercontent.com',
    iosBundleId: 'com.cwd.tiktokYt',
  );
}
